from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])        # we can also add 'PUT','POST'
def getRoutes(request):
    routes = [
        'GET/api',
        'GET/api/rooms',
        'GET/api/rooms/:id',        #to access 1 room
    ]
    return Response(routes)


# Requset to get all rooms
@api_view(['GET'])  
def getrooms(request):
    rooms = Room.objects.all()                          #Object of type Room is not JSON serializable
    serializer = RoomSerializer(rooms,many=True)        #many = True, take care that if we want to serialize multiple things and one. Here we are serializing a list of objects thats why many = True.
    # return Response(rooms)
    return Response(serializer.data)    #.data is used to access the serialized representation of the data generated by the serializer, which can then be returned in a response to the client making the HTTP request.



#Request for specific rooms
@api_view(['GET'])  
def getroom(request,id):
    room = Room.objects.get(pk=id)                          #Object of type Room is not JSON serializable
    serializer = RoomSerializer(room,many=False)        #many = True, take care that if we want to serialize multiple things and one. Here we are serializing a list of objects thats why many = True.
    # return Response(rooms)
    return Response(serializer.data)


# from django.http import JsonResponse

# def getRoutes(request):
#     routes = [
#         'GET/api',
#         'GET/api/rooms',
#         'GET/api/rooms/:id',
#     ]
#     return JsonResponse(routes,safe = False)



