# Generated by Django 4.2.5 on 2024-03-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='github.png', null=True, upload_to='profile_pics'),
        ),
    ]
