# Generated by Django 4.2.5 on 2024-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_notification_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
